### ISSUE TITLE
[bug] Panic during kubectl login

### ISSUE THREAD

**Issue by lpitstickpstg** [portworx/pxc#194]
**Describe the bug**
Panic during kubectl login

**Version**
0.34.0

WORKS on 0.33.0

**Additional Information**
```
kubectl pxc login \                                                                                                                                       [16/4997]  --k8s-secret-name=px-admin-token \
  --k8s-secret-namespace=kube-system
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x41147c]

goroutine 1 [running]:
reflect.mapiternext(0xc000111200?)
        /usr/local/go/src/runtime/map.go:1378 +0x19
github.com/modern-go/reflect2.(*UnsafeMapIterator).UnsafeNext(0x5?)
        /go/pkg/mod/github.com/modern-go/reflect2@v1.0.1/unsafe_map.go:136 +0x32
github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc000906090, 0xc0005fa1a0, 0xc000131500)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_map.go:297 +0x31a
github.com/json-iterator/go.(*placeholderEncoder).Encode(0x142a1e0?, 0xc000127a01?, 0xc000131518?)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:332 +0x22
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc000907da0, 0x1357c37?, 0xc000131500)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_encoder.go:110 +0x56
github.com/json-iterator/go.(*structEncoder).Encode(0xc000907ef0, 0xc000049680?, 0xc000131500)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_encoder.go:158 +0x765
github.com/json-iterator/go.(*placeholderEncoder).Encode(0x142a1e0?, 0xa5a701?, 0xc000131518?)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:332 +0x22
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc000934180, 0x1318b3e?, 0xc000131500)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_encoder.go:110 +0x56
github.com/json-iterator/go.(*structEncoder).Encode(0xc0009341e0, 0x13cf7c0?, 0xc000131500)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_encoder.go:158 +0x765
github.com/json-iterator/go.(*sliceEncoder).Encode(0xc0008081c8, 0xc000812478, 0xc000131500)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_slice.go:42 +0x302
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc000934d50, 0x131e687?, 0xc000131500)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_encoder.go:110 +0x56
github.com/json-iterator/go.(*structEncoder).Encode(0xc000934e40, 0x0?, 0xc000131500)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_encoder.go:158 +0x765
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc000050460?, 0x0?, 0x0?)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_optional.go:70 +0xa4
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc000461f80, 0xc000812420, 0xc0004d0870?)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:219 +0x82
github.com/json-iterator/go.(*Stream).WriteVal(0xc000131500, {0x14a70c0, 0xc000812420})
        /go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:98 +0x158
github.com/json-iterator/go.(*frozenConfig).Marshal(0xc000050460, {0x14a70c0, 0xc000812420})
        /go/pkg/mod/github.com/json-iterator/go@v1.1.10/config.go:299 +0xc9
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).doEncode(0x12fd425?, {0x182bd68?, 0xc000812420?}, {0x1823400, 0xc0008da510})
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/runtime/serializer/json/json.go:306 +0x6d
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode(0xc0001ee0f0, {0x182bd68, 0xc000812420}, {0x1823400, 0xc0008da510})
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/runtime/serializer/json/json.go:301 +0xfc
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).doEncode(0xc0001c2960, {0x182bd18?, 0xc000131440}, {0x1823400, 0xc0008da510})
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/runtime/serializer/versioning/versioning.go:244 +0x8fa
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode(0xc0001c2960, {0x182bd18, 0xc000131440}, {0x1823400, 0xc0008da510})
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/runtime/serializer/versioning/versioning.go:184 +0x106
k8s.io/apimachinery/pkg/runtime.Encode({0x7f515070f958, 0xc0001c2960}, {0x182bd18, 0xc000131440})
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/runtime/codec.go:50 +0x64
k8s.io/client-go/tools/clientcmd.Write(...)
        /go/pkg/mod/k8s.io/client-go@v0.20.4/tools/clientcmd/loader.go:473
k8s.io/client-go/tools/clientcmd.WriteToFile({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0xc000883ce0}, 0xc000883d10, 0xc000883d40, 0xc000883d70, {0xc0001be480, ...}, ...}, ...)
        /go/pkg/mod/k8s.io/client-go@v0.20.4/tools/clientcmd/loader.go:426 +0xa8
k8s.io/client-go/tools/clientcmd.ModifyConfig({0x183d938, 0xc00013e0a0}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0xc000883020}, 0xc000883050, 0xc000883080, ...}, ...)
        /go/pkg/mod/k8s.io/client-go@v0.20.4/tools/clientcmd/config.go:294 +0xcf8
github.com/portworx/pxc/pkg/config.(*KubernetesConfigManager).ModifyKubeconfig(0x1409d60?, 0xc000130840)
        /go/src/github.com/portworx/pxc/pkg/config/km.go:93 +0x9d
github.com/portworx/pxc/pkg/config.(*KubernetesConfigManager).SaveAuthInfoForKubeUser(0x1409d60?, {0xc0000493b0?, 0xc0000493b0?}, {0xc00004a0cb, 0x2b}, 0xc0004281b0)
        /go/src/github.com/portworx/pxc/pkg/config/km.go:201 +0x40a
github.com/portworx/pxc/pkg/config.(*KubernetesConfigManager).ConfigSaveAuthInfo(0xc000010648, 0xc0004281b0)
        /go/src/github.com/portworx/pxc/pkg/config/km.go:494 +0x1eb
github.com/portworx/pxc/pkg/config.(*ConfigManager).ConfigSaveAuthInfo(...)
        /go/src/github.com/portworx/pxc/pkg/config/cm.go:256
github.com/portworx/pxc/handler/login.loginExec(0xc000393180?, {0x15f4944?, 0x2?, 0x2?})
        /go/src/github.com/portworx/pxc/handler/login/login.go:66 +0x62
github.com/spf13/cobra.(*Command).execute(0xc000393180, {0xc000149ce0, 0x2, 0x2})
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00038aa00)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x39c
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/portworx/pxc/cmd.Main()
        /go/src/github.com/portworx/pxc/cmd/main.go:86 +0x16e
github.com/portworx/pxc/cmd.Execute()
        /go/src/github.com/portworx/pxc/cmd/main.go:50 +0x1d
main.main()
        /go/src/github.com/portworx/pxc/main.go:24 +0x17
/home/lpitstick/kubeup> k version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-19T17:23:01Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
```

**Comment by lpabon** [comment]
We just confirmed that this works with v0.33 but not with v0.34, so there is a regression here.
